sudo: false

language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules

before_script: npm install -g grunt-cli
after_success: "./travis-nightly.sh"
after_failure: if [ "$GH_TOKEN" ]; then grunt gh-pages:crafty-distro-regression-tests; fi

env:
  global:
  - SAUCE_BRANCH=testing
  # GitHub token
  - secure: nMIM+zttVf8rmBrI4RSvWcZiqN1rwFPt9xIY89QkRuHJeAvju9HM5N5RoossvDBQ+b/Z5Sm3L3aq+U2KfWnW5mSnAvmE2j2T4HfaQABnTiVzGhpailaX9O7ACZuLnsQ9hgbIxPOSlk68cDcAp3HWnofBYigauhWbEwbuBGWl/iU=
  # OpenSauce credentials: for pre-relase testing
  - secure: NO+7PK5P0XLGbnvdSDBlrlnzqM/hMTy3wxxAp8ZtzEuS2ZOXn8q0KjOO/cAs1NorG1SOl8+XfFZBTR5W504GrHYLP8fNkLJOAyKMfFeTojwQ+385ShVr/NejZFejsc+xJZymIeDsEzBZqosxPOi+8k7jljDK4mzLdKMpt8flWUw=
  - secure: iGO+VCkCq/26Dqrc6+G1nX8Dk+tTqhcINuiIVhxGtMARcY+WIzcyEK/cfXRaLnvIzIxQ0xUoGGnM9xe4DQT8L+BGzo8AGnVbzxITzceWTlhsFepcbOTgqOg0ZGMxQVQ6VBh888Cdks8KsOgtTNhzd+oVgcStsyxZPCVD/7VgNTE=

addons:
  sauce_connect:
    no_ssl_bump_domains: all
