# Test against this version of Node.js.
environment:
  nodejs_version: "6"

# preserve local npm and yarn modules but will reset them if package.json or appveyor.yml is modified
cache:
  - node_modules -> appveyor.yml, package.json, yarn.lock
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml, package.json, yarn.lock'

version: '{build}'

# Install scripts. (runs after repo cloning)
install:
  # Get the specified version of Node.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - yarn install
  - npm install -g grunt-cli

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - yarn --version
  # run tests
  - npm test || set FAILEDTESTS=true
after_test:
  - IF "%FAILEDTESTS%"=="true" ( echo Tests failed! & echo upload screenshots for debugging & exit 1 )

# Don't actually build.
build: off
